modLoader="javafml" #mandatory
loaderVersion="[26,)" #mandatory
issueTrackerURL="https://github.com/ToMe25/Flaming-Arrows/issues"
[[mods]] #mandatory
    modId="flamingarrows" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Flaming Arrows" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/flaming-arrows"
    logoFile="flaming_arrow_logo.png"
    credits=""
    authors="ToMe25"
    description='''A small Minecraft Vanilla+ Mod that replaces the Flame Enchantment for Bows with Flaming Arrows that can be shot with Bows and Crossbows.'''
[[dependencies.flamingarrows]]
    modId="forge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flamingarrows]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.14.4]"
    ordering="NONE"
    side="BOTH"
